apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: {{ template "appNameWithBranch" . }}-hpa
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "appNameWithBranch" . }}
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: {{ template "appNameWithBranch" . }}
    apiVersion: "apps/v1"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
