steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args: [ './1-clone.sh', $_SRC_REPO, $_BRANCH ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ './2-build.sh' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ './3-image.sh', $_BRANCH ]

#  - name: "gcr.io/cloud-builders/gke-deploy"
#    entrypoint: bash
#    args: [ './4-deploy.sh']
