steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args: [ './clone.sh', $_SOURCE_REPO ]

  - name: node
    entrypoint: bash
    args: [ './build.sh', 'nodejs12' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ './build-push-image.sh', 'nodejs12', $_BRANCH ]

  - name: "gcr.io/cloud-builders/gke-deploy"
    entrypoint: bash
    args: [ './deploy.sh']
