steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: bash
    args: [ './0-clone.sh', $_SRC_REPO_URL, $_BRANCH ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ './1-env.sh', $_BRANCH ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ './2-build.sh' ]

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args: [ './3-image.sh' ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args: [ './4-deploy.sh']
tags: [$_TAG1, $_TAG2]
options:
  substitution_option: 'ALLOW_LOOSE'
